version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/mini-project/index.js
      - ./models/user.model.js:/mini-project/backend/models/user.model.js
      - ./models/service.model.js:/mini-project/backend/models/service.model.js
    ports:
      - 3000:3000

  my-database:
    image: mongo:latest
    ports:
      - 1001:27017
